### ISSUE TITLE
A quick question.

### ISSUE THREAD

**Issue by Milo123459** [broofa/runmd#7]
Not really an issue, but when is the next update coming out? I really like this tool and it is so helpful.

I'm just waiting for some new updates!

**Comment by broofa** [comment]
Judging by the [lack of] issues and PRs people are submitting, and the fact NPM shows no dependents for this module, I seem to be the main/only real consumer of this project.  I use it on `uuid` and `mime` projects, and maybe a couple other things here and there but other than that... there's not much driving development.  Currently I have no concrete plans for new features or releases.  I'll add to it if/when I see the need but otherwise... if there's something specific you'd like to see feel free to file an issue.  Or, better still, submit a PR.

Cheers!

**Comment by Milo123459** [comment]
What! I use the cli on a day-to-do basis! Man, don't give up on this project.. 
If you need help with it, hit me up and I'd be happy to help!
